object Versions {
    const val ANDROID_CORE = "1.7.0"
    const val ANDROID_COMPAT = "1.5.1"
    const val ANDROID_NAVIGATION = "2.5.3"
    const val ANDROID_VIEWMODEL_KTX = "2.5.1"
    const val ANDROID_LIFECYCLE_KTX = "2.5.1"
    const val ANDROID_FRAGMENT_KTX = "1.5.4"
    const val ANDROID_DATASTORE = "1.0.0"
    const val ROOM = "2.4.3"
    const val HILT = "2.44"
    const val OKHTTP = "4.9.0"
    const val RETROFIT = "2.9.0"
    const val TIMBER = "5.0.1"
    const val ML_KIT = "17.0.2"
    const val GLIDE = "4.14.2"
    const val METERIAL = "1.7.0"
    const val GSON = "2.9.0"
}